config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end

  def new
    @product=Product.new
  end

  def create
  	if @product = product_params
  	end
  end

  private
  def product_params
    params.require(:product).permit(:shopname, :title, :description,)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<%= link_to 'Shop', new_product_path%>

app/views/products/new.html.erb
<%= form_for @product do |f| %>
   <p>
    <%= f.label :shopname %><br />
    <%= f.text_field :shopname %>
  </p>
   <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>